//! `mge setup` — a guided first-run wizard: collect the user's own (free) API
//! keys, detect the GPU, and write a ready-to-use config with task-tier routes
//! and auto-routing enabled. The whole point: anyone can be running in a minute.

use crate::config::Config;
use crate::{gpu, theme};
use anyhow::Result;
use std::collections::BTreeMap;
use std::io::Write;
use std::path::PathBuf;

pub fn run() -> Result<()> {
    use theme::ansi::*;
    print!("{}", theme::banner(env!("CARGO_PKG_VERSION")));
    println!("{SKY}Let's set up MGE_GOAT — free models, your keys.{RESET}\n");

    match gpu::summary() {
        Some(s) => println!(
            "GPU detected: {s}\n  (you can run models locally too — see docs/LOCAL_LLAMA.md)"
        ),
        None => println!("No GPU detected — MGE_GOAT will use free remote APIs."),
    }
    println!();
    println!("{DIM}Paste your key and press Enter, or just press Enter to skip a provider.{RESET}");

    let openrouter = prompt("OpenRouter key  (https://openrouter.ai/keys) : ")?;
    let nim = prompt("NVIDIA NIM key  (https://build.nvidia.com)  : ")?;

    if openrouter.is_empty() && nim.is_empty() && read_secrets().unwrap_or_default().is_empty() {
        println!(
            "\n{STRAWBERRY}No keys provided — you'll need at least one to use remote models.{RESET}"
        );
        println!("Re-run {SKY}mge setup{RESET} anytime, or edit ~/.config/mge/secrets.env.");
    }

    // Merge into existing secrets (don't clobber a key the user skipped).
    let mut secrets = read_secrets().unwrap_or_default();
    if !openrouter.is_empty() {
        secrets.insert("OPENROUTER_API_KEY".into(), openrouter);
    }
    if !nim.is_empty() {
        secrets.insert("NVIDIA_NIM_API_KEY".into(), nim);
    }
    write_secrets(&secrets)?;

    let path = Config::default_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, CONFIG_TEMPLATE)?;

    println!("\n{PISTACHIO}✓ config  → {}{RESET}", path.display());
    println!("{PISTACHIO}✓ secrets → ~/.config/mge/secrets.env (chmod 600){RESET}");
    println!(
        "\nRoutes: {SKY}fast / main / heavy{RESET} with auto-routing ON (it picks per task).\n\
         Verify with {SKY}mge doctor{RESET}, then launch {SKY}mge tui{RESET}.  🐐🍦"
    );
    Ok(())
}

fn prompt(label: &str) -> Result<String> {
    print!("{label}");
    std::io::stdout().flush().ok();
    let mut s = String::new();
    std::io::stdin().read_line(&mut s)?;
    Ok(s.trim().to_string())
}

fn secrets_path() -> Result<PathBuf> {
    let cfg = Config::default_path()?;
    Ok(cfg
        .parent()
        .expect("config has a parent dir")
        .join("secrets.env"))
}

fn read_secrets() -> Result<BTreeMap<String, String>> {
    let mut m = BTreeMap::new();
    let Ok(raw) = std::fs::read_to_string(secrets_path()?) else {
        return Ok(m);
    };
    for line in raw.lines() {
        let line = line.trim();
        let line = line.strip_prefix("export ").unwrap_or(line);
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_string(), v.trim().trim_matches('"').to_string());
        }
    }
    Ok(m)
}

fn write_secrets(m: &BTreeMap<String, String>) -> Result<()> {
    let path = secrets_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut out = String::from(
        "# MGE_GOAT secrets — loaded by `mge` at startup. chmod 600. Do NOT commit.\n",
    );
    for (k, v) in m {
        out.push_str(&format!("export {k}=\"{v}\"\n"));
    }

    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        use std::os::unix::fs::PermissionsExt;
        // Create with 0o600 from the start so the secrets file is never briefly
        // world-readable (no TOCTOU window); also fix perms on a pre-existing file.
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&path)?;
        f.write_all(out.as_bytes())?;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
    }
    #[cfg(not(unix))]
    std::fs::write(&path, out)?;
    Ok(())
}

const CONFIG_TEMPLATE: &str = r#"# MGE_GOAT configuration 🐐🍦 (generated by `mge setup`)
default_route = "main"
auto_route = true   # pick fast/main/heavy per task automatically

[providers.openrouter]
kind = "openai"
base_url = "https://openrouter.ai/api/v1"
api_key_env = "OPENROUTER_API_KEY"

[providers.nim]
kind = "openai"
base_url = "https://integrate.api.nvidia.com/v1"
api_key_env = "NVIDIA_NIM_API_KEY"

[providers.local]
kind = "openai"
base_url = "http://localhost:8080/v1"
api_key_env = "NONE"
local = true

# ── Task tiers (verified free, tool-capable model ids) ───────────────────────
[models.main]        # default coding model
provider = "openrouter"
model = "qwen/qwen3-coder:free"
fallback = ["heavy", "fast", "nim"]

[models.heavy]       # reasoning-heavy tasks
provider = "openrouter"
model = "openai/gpt-oss-120b:free"
fallback = ["main", "nim"]

[models.fast]        # light / trivial tasks
provider = "openrouter"
model = "nvidia/nemotron-nano-9b-v2:free"
fallback = ["main"]

[models.nim]         # NVIDIA NIM alternative
provider = "nim"
model = "qwen/qwen3.5-122b-a10b"

# [models.local]     # see docs/LOCAL_LLAMA.md to run llama.cpp on your GPU
# provider = "local"
# model = "local"
# min_free_vram_mb = 4000
"#;
